let catindad = 20000;
let porcentaje = 60;
let resultado = (catindad * porcentaje)  / 100;
console.log(resultado);
let divison = resultado / 5;
console.log(divison);
let divisonDos = catindad / 5;
console.log(divisonDos);
let total = divisonDos + divison;
console.log(total);